### ISSUE TITLE
Training job failed

### ISSUE THREAD

**Issue by wjmuse** [awslabs/predictive-maintenance-using-machine-learning#6] opened 2020-02-27 09:20 UTC
Hi team,

I create CloudFormation Stack from this page:
https://aws.amazon.com/solutions/predictive-maintenance-using-machine-learning/

and start to run the notebook and executed the training job, but there is an error accured:

```
Invoking script with the following command:

/usr/bin/python -m sagemaker_predictive_maintenance_entry_point --batch-size 1 --epochs 500 --log-interval 100 --num-datasets 4 --num-gpus 1 --optimizer adam


Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/ml/code/sagemaker_predictive_maintenance_entry_point.py", line 10, in <module>
    import gluonnlp
  File "/usr/local/lib/python3.5/dist-packages/gluonnlp/__init__.py", line 25, in <module>
    from . import data
  File "/usr/local/lib/python3.5/dist-packages/gluonnlp/data/__init__.py", line 23, in <module>
    from . import (batchify, candidate_sampler, conll, corpora, dataloader,
  File "/usr/local/lib/python3.5/dist-packages/gluonnlp/data/question_answering.py", line 31, in <module>
    from mxnet.gluon.utils import download, check_sha1, _get_repo_file_url, replace_file
ImportError: cannot import name 'replace_file'
2020-02-27 09:04:17,944 sagemaker-containers ERROR    ExecuteUserScriptError:
Command "/usr/bin/python -m sagemaker_predictive_maintenance_entry_point --batch-size 1 --epochs 500 --log-interval 100 --num-datasets 4 --num-gpus 1 --optimizer adam"

2020-02-27 09:04:31 Failed - Training job failed

```

Could you please help on check this error? Thanks!

**Comment by lffa** [comment] 2020-03-05 08:04
I have got the same error ...

**Comment by markzhu1974** [comment] 2020-03-15 16:00
I've got the same error too.

**Comment by markzhu1974** [comment] 2020-03-29 16:35
Under the "Train MXNet Estimator" cell in the notebook, change the framework_version from 1.3.0 to 1.6.0, then the training job can get success.

framework_version='1.6.0'

**Comment by lffa** [comment] 2020-03-31 12:07
thanks, it works for me as well when changing the framework.

**Comment by eleyeth** [comment] 2020-04-15 20:43
> Under the "Train MXNet Estimator" cell in the notebook, change the framework_version from 1.3.0 to 1.6.0, then the training job can get success.
> 
> framework_version='1.6.0'

I tried this but it did not solve the problem

**Comment by vishaalkapoor** [comment] 2020-04-17 21:16
Looking into this.

**Comment by vishaalkapoor** [comment] 2020-04-17 22:29
@eleyeth Would you be able to post the log after this cell below. I think you're seeing a different error than the others due to both the requirements.txt file and framework_version setting mxnet version.

```
from sagemaker.mxnet import MXNet

training_job_name = 'delete-4-pred-maintenance-mxnet-model3'
train_instance_type = 'ml.p3.2xlarge'

m = MXNet(entry_point='sagemaker_predictive_maintenance_entry_point.py',
          source_dir='sagemaker_predictive_maintenance_entry_point',
          py_version='py3',
          role=role, 
          train_instance_count=1, 
          train_instance_type=train_instance_type,
          output_path=output_location,
          hyperparameters={'num-datasets' : len(train_df),
                           'num-gpus': 1,
                           'epochs': 500,
                           'optimizer': 'adam',
                           'batch-size':1,
                           'log-interval': 100},
         input_mode='File',
         train_max_run=7200,
         framework_version='1.6.0')

m.fit({'train': s3_train_data}, job_name=training_job_name)
```
E.g.
```
2020-04-17 22:21:20 Starting - Starting the training job...
2020-04-17 22:21:22 Starting - Launching requested ML instances......
2020-04-17 22:22:27 Starting - Preparing the instances for training......
2020-04-17 22:23:30 Downloading - Downloading input data...
2020-04-17 22:24:09 Training - Downloading the training image...
2020-04-17 22:24:51 Training - Training image download completed. Training in progress..2020-04-17 22:24:51,561 sagemaker-containers INFO     Imported framework sagemaker_mxnet_container.training
2020-04-17 22:24:51,588 sagemaker_mxnet_container.training INFO     MXNet training environment: {'SM_HOSTS': '["algo-1"]', 'SM_NETWORK_INTERFACE_NAME': 'eth0', 'SM_HPS': '{"batch-size":1,"epochs":500,"log-interval":100,"num-datasets":4,"num-gpus":1,"optimizer":"adam"}', 'SM_USER_ENTRY_POINT': 'sagemaker_predictive_maintenance_entry_point.py', 'SM_FRAMEWORK_PARAMS': '{}', 'SM_RESOURCE_CONFIG': '{"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"eth0"}', 'SM_INPUT_DATA_CONFIG': '{"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}', 'SM_OUTPUT_DATA_DIR': '/opt/ml/output/data', 'SM_CHANNELS': '["train"]', 'SM_CURRENT_HOST': 'algo-1', 'SM_MODULE_NAME': 'sagemaker_predictive_maintenance_entry_point', 'SM_LOG_LEVEL': '20', 'SM_FRAMEWORK_MODULE': 'sagemaker_mxnet_container.training:main', 'SM_INPUT_DIR': '/opt/ml/input', 'SM_INPUT_CONFIG_DIR': '/opt/ml/input/config', 'SM_OUTPUT_DIR': '/opt/ml/output', 'SM_NUM_CPUS': '8', 'SM_NUM_GPUS': '1', 'SM_MODEL_DIR': '/opt/ml/model', 'SM_MODULE_DIR': 's3://delete-4-model/delete-4-pred-maintenance-mxnet-model3/source/sourcedir.tar.gz', 'SM_TRAINING_ENV': '{"additional_framework_parameters":{},"channel_input_dirs":{"train":"/opt/ml/input/data/train"},"current_host":"algo-1","framework_module":"sagemaker_mxnet_container.training:main","hosts":["algo-1"],"hyperpara
```

I can confirm that updating the framework_version to 1.6.0 will fix the main error, but the requirements.txt file is calling for cuda 9.0 instead of 9.2. I'm going to put in a PR that removes mxnet from the requirements file and uses only the framework_version.

**Comment by vishaalkapoor** [comment] 2020-04-18 02:11
Note: the AWS Solution will be officially updated early next week. Code is merged into GitHub in the meantime. To use this code, you'll need to `git clone` this repository into SageMaker, for example via the terminal or using Git integration. Feel free to ping me if you have questions.

**Comment by eleyeth** [comment] 2020-04-21 18:56
> @eleyeth Would you be able to post the log after this cell below. I think you're seeing a different error than the others due to both the requirements.txt file and framework_version setting mxnet version.
> 
> ```
> from sagemaker.mxnet import MXNet
> 
> training_job_name = 'delete-4-pred-maintenance-mxnet-model3'
> train_instance_type = 'ml.p3.2xlarge'
> 
> m = MXNet(entry_point='sagemaker_predictive_maintenance_entry_point.py',
>           source_dir='sagemaker_predictive_maintenance_entry_point',
>           py_version='py3',
>           role=role, 
>           train_instance_count=1, 
>           train_instance_type=train_instance_type,
>           output_path=output_location,
>           hyperparameters={'num-datasets' : len(train_df),
>                            'num-gpus': 1,
>                            'epochs': 500,
>                            'optimizer': 'adam',
>                            'batch-size':1,
>                            'log-interval': 100},
>          input_mode='File',
>          train_max_run=7200,
>          framework_version='1.6.0')
> 
> m.fit({'train': s3_train_data}, job_name=training_job_name)
> ```
> 
> E.g.
> 
> ```
> 2020-04-17 22:21:20 Starting - Starting the training job...
> 2020-04-17 22:21:22 Starting - Launching requested ML instances......
> 2020-04-17 22:22:27 Starting - Preparing the instances for training......
> 2020-04-17 22:23:30 Downloading - Downloading input data...
> 2020-04-17 22:24:09 Training - Downloading the training image...
> 2020-04-17 22:24:51 Training - Training image download completed. Training in progress..2020-04-17 22:24:51,561 sagemaker-containers INFO     Imported framework sagemaker_mxnet_container.training
> 2020-04-17 22:24:51,588 sagemaker_mxnet_container.training INFO     MXNet training environment: {'SM_HOSTS': '["algo-1"]', 'SM_NETWORK_INTERFACE_NAME': 'eth0', 'SM_HPS': '{"batch-size":1,"epochs":500,"log-interval":100,"num-datasets":4,"num-gpus":1,"optimizer":"adam"}', 'SM_USER_ENTRY_POINT': 'sagemaker_predictive_maintenance_entry_point.py', 'SM_FRAMEWORK_PARAMS': '{}', 'SM_RESOURCE_CONFIG': '{"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"eth0"}', 'SM_INPUT_DATA_CONFIG': '{"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}', 'SM_OUTPUT_DATA_DIR': '/opt/ml/output/data', 'SM_CHANNELS': '["train"]', 'SM_CURRENT_HOST': 'algo-1', 'SM_MODULE_NAME': 'sagemaker_predictive_maintenance_entry_point', 'SM_LOG_LEVEL': '20', 'SM_FRAMEWORK_MODULE': 'sagemaker_mxnet_container.training:main', 'SM_INPUT_DIR': '/opt/ml/input', 'SM_INPUT_CONFIG_DIR': '/opt/ml/input/config', 'SM_OUTPUT_DIR': '/opt/ml/output', 'SM_NUM_CPUS': '8', 'SM_NUM_GPUS': '1', 'SM_MODEL_DIR': '/opt/ml/model', 'SM_MODULE_DIR': 's3://delete-4-model/delete-4-pred-maintenance-mxnet-model3/source/sourcedir.tar.gz', 'SM_TRAINING_ENV': '{"additional_framework_parameters":{},"channel_input_dirs":{"train":"/opt/ml/input/data/train"},"current_host":"algo-1","framework_module":"sagemaker_mxnet_container.training:main","hosts":["algo-1"],"hyperpara
> ```
> 
> I can confirm that updating the framework_version to 1.6.0 will fix the main error, but the requirements.txt file is calling for cuda 9.0 instead of 9.2. I'm going to put in a PR that removes mxnet from the requirements file and uses only the framework_version.

This was my log: 
2020-04-15 20:21:37 Starting - Starting the training job...
2020-04-15 20:21:40 Starting - Launching requested ML instances......
2020-04-15 20:22:46 Starting - Preparing the instances for training......
2020-04-15 20:23:59 Downloading - Downloading input data
2020-04-15 20:23:59 Training - Downloading the training image......
2020-04-15 20:25:03 Training - Training image download completed. Training in progress..2020-04-15 20:25:03,851 sagemaker-containers INFO Imported framework sagemaker_mxnet_container.training
2020-04-15 20:25:03,879 sagemaker_mxnet_container.training INFO MXNet training environment: {'SM_HOSTS': '["algo-1"]', 'SM_NETWORK_INTERFACE_NAME': 'eth0', 'SM_HPS': '{"batch-size":1,"epochs":500,"log-interval":100,"num-datasets":4,"num-gpus":1,"optimizer":"adam"}', 'SM_USER_ENTRY_POINT': 'sagemaker_predictive_maintenance_entry_point.py', 'SM_FRAMEWORK_PARAMS': '{}', 'SM_RESOURCE_CONFIG': '{"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"eth0"}', 'SM_INPUT_DATA_CONFIG': '{"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}', 'SM_OUTPUT_DATA_DIR': '/opt/ml/output/data', 'SM_CHANNELS': '["train"]', 'SM_CURRENT_HOST': 'algo-1', 'SM_MODULE_NAME': 'sagemaker_predictive_maintenance_entry_point', 'SM_LOG_LEVEL': '20', 'SM_FRAMEWORK_MODULE': 'sagemaker_mxnet_container.training:main', 'SM_INPUT_DIR': '/opt/ml/input', 'SM_INPUT_CONFIG_DIR': '/opt/ml/input/config', 'SM_OUTPUT_DIR': '/opt/ml/output', 'SM_NUM_CPUS': '8', 'SM_NUM_GPUS': '1', 'SM_MODEL_DIR': '/opt/ml/model', 'SM_MODULE_DIR': 's3://ascendpred/pred-maintenance-mxnet-modelv11/source/sourcedir.tar.gz', 'SM_TRAINING_ENV': '{"additional_framework_parameters":{},"channel_input_dirs":{"train":"/opt/ml/input/data/train"},"current_host":"algo-1","framework_module":"sagemaker_mxnet_container.training:main","hosts":["algo-1"],"hyperparameters":{"batch-size":1,"epochs":500,"log-interval":100,"num-datasets":4,"num-gpus":1,"optimizer":"adam"},"input_config_dir":"/opt/ml/input/config","input_data_config":{"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}},"input_dir":"/opt/ml/input","is_master":true,"job_name":"pred-maintenance-mxnet-modelv11","log_level":20,"master_hostname":"algo-1","model_dir":"/opt/ml/model","module_dir":"s3://ascendpred/pred-maintenance-mxnet-modelv11/source/sourcedir.tar.gz","module_name":"sagemaker_predictive_maintenance_entry_point","network_interface_name":"eth0","num_cpus":8,"num_gpus":1,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"eth0"},"user_entry_point":"sagemaker_predictive_maintenance_entry_point.py"}', 'SM_USER_ARGS': '["--batch-size","1","--epochs","500","--log-interval","100","--num-datasets","4","--num-gpus","1","--optimizer","adam"]', 'SM_OUTPUT_INTERMEDIATE_DIR': '/opt/ml/output/intermediate', 'SM_CHANNEL_TRAIN': '/opt/ml/input/data/train', 'SM_HP_BATCH-SIZE': '1', 'SM_HP_LOG-INTERVAL': '100', 'SM_HP_OPTIMIZER': 'adam', 'SM_HP_NUM-DATASETS': '4', 'SM_HP_NUM-GPUS': '1', 'SM_HP_EPOCHS': '500'}
2020-04-15 20:25:04,158 sagemaker-containers INFO Module default_user_module_name does not provide a setup.py.
Generating setup.py
2020-04-15 20:25:04,158 sagemaker-containers INFO Generating setup.cfg
2020-04-15 20:25:04,158 sagemaker-containers INFO Generating MANIFEST.in
2020-04-15 20:25:04,158 sagemaker-containers INFO Installing module with the following command:
/usr/local/bin/python3.6 -m pip install . -r requirements.txt
Processing /tmp/tmpyb5_i2kw/module_dir
Collecting mxnet-cu90mkl>=1.4
Downloading https://files.pythonhosted.org/packages/ad/38/e1dd60173e4a2d3398fb982e873423fc62321b97db0a57c36ef889df5135/mxnet_cu90mkl-1.5.1.post0-py2.py3-none-manylinux1_x86_64.whl (525.2MB)
Requirement already satisfied: gluonnlp in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (0.9.1)
Collecting pandas==0.22
Downloading https://files.pythonhosted.org/packages/da/c6/0936bc5814b429fddb5d6252566fe73a3e40372e6ceaf87de3dec1326f28/pandas-0.22.0-cp36-cp36m-manylinux1_x86_64.whl (26.2MB)
Requirement already satisfied: requests<3,>=2.20.0 in /usr/local/lib/python3.6/site-packages (from mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: numpy<2.0.0,>1.16.0 in /usr/local/lib/python3.6/site-packages (from mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (1.17.2)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /usr/local/lib/python3.6/site-packages (from mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (0.8.4)
Requirement already satisfied: cython in /usr/local/lib/python3.6/site-packages (from gluonnlp->-r requirements.txt (line 2)) (0.29.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from gluonnlp->-r requirements.txt (line 2)) (20.3)
Requirement already satisfied: python-dateutil>=2 in /usr/local/lib/python3.6/site-packages (from pandas==0.22->-r requirements.txt (line 3)) (2.8.0)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.6/site-packages (from pandas==0.22->-r requirements.txt (line 3)) (2019.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests<3,>=2.20.0->mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests<3,>=2.20.0->mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests<3,>=2.20.0->mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests<3,>=2.20.0->mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (2019.11.28)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->gluonnlp->-r requirements.txt (line 2)) (2.4.6)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from packaging->gluonnlp->-r requirements.txt (line 2)) (1.14.0)
Installing collected packages: mxnet-cu90mkl, pandas, default-user-module-name
Found existing installation: pandas 0.25.1
Uninstalling pandas-0.25.1:
Successfully uninstalled pandas-0.25.1
Running setup.py install for default-user-module-name: started
Running setup.py install for default-user-module-name: finished with status 'done'
Successfully installed default-user-module-name-1.0.0 mxnet-cu90mkl-1.5.1.post0 pandas-0.22.0
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
2020-04-15 20:25:37,520 sagemaker-containers INFO Invoking user script

Training Env:

{
"additional_framework_parameters": {},
"channel_input_dirs": {
"train": "/opt/ml/input/data/train"
},
"current_host": "algo-1",
"framework_module": "sagemaker_mxnet_container.training:main",
"hosts": [
"algo-1"
],
"hyperparameters": {
"batch-size": 1,
"log-interval": 100,
"optimizer": "adam",
"num-datasets": 4,
"num-gpus": 1,
"epochs": 500
},
"input_config_dir": "/opt/ml/input/config",
"input_data_config": {
"train": {
"TrainingInputMode": "File",
"S3DistributionType": "FullyReplicated",
"RecordWrapperType": "None"
}
},
"input_dir": "/opt/ml/input",
"is_master": true,
"job_name": "pred-maintenance-mxnet-modelv11",
"log_level": 20,
"master_hostname": "algo-1",
"model_dir": "/opt/ml/model",
"module_dir": "s3://ascendpred/pred-maintenance-mxnet-modelv11/source/sourcedir.tar.gz",
"module_name": "sagemaker_predictive_maintenance_entry_point",
"network_interface_name": "eth0",
"num_cpus": 8,
"num_gpus": 1,
"output_data_dir": "/opt/ml/output/data",
"output_dir": "/opt/ml/output",
"output_intermediate_dir": "/opt/ml/output/intermediate",
"resource_config": {
"current_host": "algo-1",
"hosts": [
"algo-1"
],
"network_interface_name": "eth0"
},
"user_entry_point": "sagemaker_predictive_maintenance_entry_point.py"
}

Environment variables:

SM_HOSTS=["algo-1"]
SM_NETWORK_INTERFACE_NAME=eth0
SM_HPS={"batch-size":1,"epochs":500,"log-interval":100,"num-datasets":4,"num-gpus":1,"optimizer":"adam"}
SM_USER_ENTRY_POINT=sagemaker_predictive_maintenance_entry_point.py
SM_FRAMEWORK_PARAMS={}
SM_RESOURCE_CONFIG={"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"eth0"}
SM_INPUT_DATA_CONFIG={"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}
SM_OUTPUT_DATA_DIR=/opt/ml/output/data
SM_CHANNELS=["train"]
SM_CURRENT_HOST=algo-1
SM_MODULE_NAME=sagemaker_predictive_maintenance_entry_point
SM_LOG_LEVEL=20
SM_FRAMEWORK_MODULE=sagemaker_mxnet_container.training:main
SM_INPUT_DIR=/opt/ml/input
SM_INPUT_CONFIG_DIR=/opt/ml/input/config
SM_OUTPUT_DIR=/opt/ml/output
SM_NUM_CPUS=8
SM_NUM_GPUS=1
SM_MODEL_DIR=/opt/ml/model
SM_MODULE_DIR=s3://ascendpred/pred-maintenance-mxnet-modelv11/source/sourcedir.tar.gz
SM_TRAINING_ENV={"additional_framework_parameters":{},"channel_input_dirs":{"train":"/opt/ml/input/data/train"},"current_host":"algo-1","framework_module":"sagemaker_mxnet_container.training:main","hosts":["algo-1"],"hyperparameters":{"batch-size":1,"epochs":500,"log-interval":100,"num-datasets":4,"num-gpus":1,"optimizer":"adam"},"input_config_dir":"/opt/ml/input/config","input_data_config":{"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}},"input_dir":"/opt/ml/input","is_master":true,"job_name":"pred-maintenance-mxnet-modelv11","log_level":20,"master_hostname":"algo-1","model_dir":"/opt/ml/model","module_dir":"s3://ascendpred/pred-maintenance-mxnet-modelv11/source/sourcedir.tar.gz","module_name":"sagemaker_predictive_maintenance_entry_point","network_interface_name":"eth0","num_cpus":8,"num_gpus":1,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"eth0"},"user_entry_point":"sagemaker_predictive_maintenance_entry_point.py"}
SM_USER_ARGS=["--batch-size","1","--epochs","500","--log-interval","100","--num-datasets","4","--num-gpus","1","--optimizer","adam"]
SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
SM_CHANNEL_TRAIN=/opt/ml/input/data/train
SM_HP_BATCH-SIZE=1
SM_HP_LOG-INTERVAL=100
SM_HP_OPTIMIZER=adam
SM_HP_NUM-DATASETS=4
SM_HP_NUM-GPUS=1
SM_HP_EPOCHS=500
PYTHONPATH=/opt/ml/code:/usr/local/bin:/usr/local/lib/python36.zip:/usr/local/lib/python3.6:/usr/local/lib/python3.6/lib-dynload:/usr/local/lib/python3.6/site-packages

Invoking script with the following command:

/usr/local/bin/python3.6 sagemaker_predictive_maintenance_entry_point.py --batch-size 1 --epochs 500 --log-interval 100 --num-datasets 4 --num-gpus 1 --optimizer adam

Traceback (most recent call last):
File "sagemaker_predictive_maintenance_entry_point.py", line 8, in
import mxnet as mx
File "/usr/local/lib/python3.6/site-packages/mxnet/init.py", line 24, in
from .context import Context, current_context, cpu, gpu, cpu_pinned
File "/usr/local/lib/python3.6/site-packages/mxnet/context.py", line 24, in
from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
File "/usr/local/lib/python3.6/site-packages/mxnet/base.py", line 213, in
_LIB = _load_lib()
File "/usr/local/lib/python3.6/site-packages/mxnet/base.py", line 204, in _load_lib
lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
File "/usr/local/lib/python3.6/ctypes/init.py", line 348, in init
self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.9.0: cannot open shared object file: No such file or directory
2020-04-15 20:25:37,778 sagemaker-containers ERROR ExecuteUserScriptError:
Command "/usr/local/bin/python3.6 sagemaker_predictive_maintenance_entry_point.py --batch-size 1 --epochs 500 --log-interval 100 --num-datasets 4 --num-gpus 1 --optimizer adam"
Traceback (most recent call last):
File "/usr/local/bin/dockerd-entrypoint.py", line 20, in
subprocess.check_call(shlex.split(' '.join(sys.argv[1:])))
File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['train']' returned non-zero exit status 1.

2020-04-15 20:25:51 Uploading - Uploading generated training model
2020-04-15 20:25:51 Failed - Training job failed
UnexpectedStatusException Traceback (most recent call last)
in ()
21 framework_version='1.6.0')
22
---> 23 m.fit({'train': s3_train_data}, job_name=training_job_name)

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
463 self.jobs.append(self.latest_training_job)
464 if wait:
--> 465 self.latest_training_job.wait(logs=logs)
466
467 def _compilation_job_name(self):

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
1056 # If logs are requested, call logs_for_jobs.
1057 if logs != "None":
-> 1058 self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
1059 else:
1060 self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll, log_type)
3019
3020 if wait:
-> 3021 self._check_job_status(job_name, description, "TrainingJobStatus")
3022 if dot:
3023 print()

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
2613 ),
2614 allowed_statuses=["Completed", "Stopped"],
-> 2615 actual_status=status,
2616 )
2617

UnexpectedStatusException: Error for Training job pred-maintenance-mxnet-modelv11: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
Command "/usr/local/bin/python3.6 sagemaker_predictive_maintenance_entry_point.py --batch-size 1 --epochs 500 --log-interval 100 --num-datasets 4 --num-gpus 1 --optimizer adam"

**Comment by eleyeth** [comment] 2020-04-21 19:03
> Note: the AWS Solution will be officially updated early next week. Code is merged into GitHub in the meantime. To use this code, you'll need to `git clone` this repository into SageMaker, for example via the terminal or using Git integration. Feel free to ping me if you have questions.

Okay, great. thanks. 

the other issue i am having now is 'create transformer model' is not working

**Comment by sumit-dige** [comment] 2020-04-28 11:22
Vishal has given great guidance on job failure and it worked for us. here is the link for our problem and the solution also 
[StackOverflow](https://stackoverflow.com/questions/61389632/import-error-while-executing-aws-predictive-maintenance-using-machine-learning-s)

**Comment by vishaalkapoor** [comment] 2020-04-28 19:13
> > Note: the AWS Solution will be officially updated early next week. Code is merged into GitHub in the meantime. To use this code, you'll need to `git clone` this repository into SageMaker, for example via the terminal or using Git integration. Feel free to ping me if you have questions.
> 
> Okay, great. thanks.
> 
> the other issue i am having now is 'create transformer model' is not working

Hi @eleyeth Apologies for the delay. We're taking a look at this case. Will get back to you soon.

**Comment by vishaalkapoor** [comment] 2020-05-05 08:17
Hi @eleyeth and others, a fix for the "transform issue" was just checked into Git. This is being deployed to the official solution, but you can git clone this repo within your workspace on SageMaker to pull in the latest code.

**Commit** https://github.com/awslabs/predictive-maintenance-using-machine-learning/commit/52b85fe3b9d7245d9f478f74fa4fa1a583f36685**

**Comment by sumit-dige** [comment] 2020-05-18 07:50
After fixing 

> ImportError: cannot import name 'replace_file' on line from mxnet.gluon.utils import download, check_sha1, _get_repo_file_url, replace_file.

 the training job is executed but while running the Batch Transfer job we are facing following errors.

> W-9001-model com.amazonaws.ml.mms.wlm.BatchAggregator - Load model failed: model, error: Worker died

> OSError: libcudart.so.10.1: cannot open shared object file

**Comment by sojiadeshina** [comment] 2020-05-18 15:20
hi sumit, 
can you provide some steps to reproduce your batch transform error. specifically, are you using the same exact function call in the notebooks or have you made some slight changes. for example are you deploying to a gpu instance for inference?

**Comment by sumit-dige** [comment] 2020-05-19 06:07
Hi Sojiadeshina,

We have changed the notebook as per the answer provided on [StackOverflow](https://stackoverflow.com/questions/61389632/import-error-while-executing-aws-predictive-maintenance-using-machine-learning-s)
As per the answer we have updated the **framework_version** to **1.6.0** from 1.3.0 in notebook and updated the requirement.txt with following.
**mxnet-cu101mkl==1.6
gluonnlp==0.9.1
pandas==0.22**
Apart from this we have not changed anything.

**Comment by sumit-dige** [comment] 2020-05-19 13:06
We have found the way, we removed the mxnet-cu101mkl==1.6 from requirement.txt which lead us to the result. Cheers

**Comment by sojiadeshina** [comment] 2020-09-14 07:08
Closing as the issue is now resolved.

**Closed as completed by sojiadeshina** 2020-09-14 07:08 UTC
